services:
  fed-mgr:
    image: harbor.cloud.infn.it/datacloud-middleware/fed-mgr:python3.12
    container_name: fed-mgr
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      opa:
        condition: service_started
    ports:
      - 8000:80
    environment:
      DB_SCHEME: mysql+pymysql
      DB_USER: fed-mgr
      DB_PASSWORD: changeit
      DB_HOST: db
      DB_NAME: fed_mgr
      AUTHN_MODE: local
      AUTHZ_MODE: opa
      TRUSTED_IDP_LIST: '["https://iam.cloud.infn.it/"]'
      OPA_AUTHZ_URL: http://opa:8181/v1/data/fed_mgr
      SECRET_KEY: changeit
    volumes:
      - ../certs:/certs:ro
    networks:
      - fed-mgr-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health/"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3

  db:
    image: mysql:8
    container_name: fed-mgr-db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeit
      MYSQL_DATABASE: fed_mgr
      MYSQL_USER: fed-mgr
      MYSQL_PASSWORD: changeit
    networks:
      - fed-mgr-net
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}",
          "--silent",
        ]
      interval: 5s
      timeout: 5s
      retries: 50

  opa:
    image: openpolicyagent/opa
    container_name: opa
    ports:
      - 8181:8181
    volumes:
      - ../opa/data:/fed_mgr:ro
    command: run --server --log-level debug --addr 0.0.0.0:8181 /fed_mgr
    networks:
      - fed-mgr-net

networks:
  fed-mgr-net:

volumes:
  db-data:
